---
- include_tasks: install.yml
  tags: strongswan-install

- include_tasks: ssl-certs.yml
  tags: strongswan-install

- include_tasks: download-cert.yml
  tags: strongswan-download-cert
  when: strongswan_client and strongswan_download_cert

- include_tasks: upload-cert.yml
  tags: strongswan-upload-cert
  when: strongswan_client and strongswan_upload_cert

- include_tasks: config.yml
  tags: strongswan-config
